"""add badges table

Revision ID: 480bf96b774d
Revises: e19dd989d149
Create Date: 2026-09-06 18:46:41.742367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '480bf96b774d'
down_revision: Union[str, None] = 'e19dd989d149'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('driver_id', sa.Uuid(), nullable=False),
    sa.Column('tier', sa.Enum('PLATINUM', 'GOLD', 'SILVER', 'BRONZE', 'AT_RISK', 'SUSPENDED', name='badgetier'), nullable=False),
    sa.Column('safety_score', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('driver_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('badges')
    # ### end Alembic commands ###
