"""add violations, fines, and license points

Revision ID: 727c78b70629
Revises: fa7391ba98d1
Create Date: 2026-09-03 04:37:41.687194

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "727c78b70629"
down_revision: Union[str, None] = "fa7391ba98d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "violations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("driver_id", sa.Uuid(), nullable=False),
        sa.Column("officer_id", sa.Uuid(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "WHITE_LINE",
                "SPEEDING",
                "RED_LIGHT",
                "DRUNK_DRIVING",
                name="violationtype",
            ),
            nullable=False,
        ),
        sa.Column("points_deducted", sa.Integer(), nullable=False),
        sa.Column("evidence_ref", sa.Text(), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["driver_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["officer_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_violations_driver_id"), "violations", ["driver_id"], unique=False
    )
    op.create_table(
        "fines",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("violation_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("UNPAID", "PAID", "REVERSED", name="finestatus"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("paid_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["violation_id"], ["violations.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("violation_id"),
    )
    # server_default backfills existing rows -- Python-side default=0 only
    # applies to new inserts, not this ALTER TABLE against already-issued licenses.
    op.add_column(
        "licenses",
        sa.Column("points", sa.Integer(), nullable=False, server_default="0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("licenses", "points")
    op.drop_table("fines")
    op.drop_index(op.f("ix_violations_driver_id"), table_name="violations")
    op.drop_table("violations")
    # ### end Alembic commands ###
