"""add vehicle categories to licenses and applications

Revision ID: cd6391130c4f
Revises: ffecd4ec72e8
Create Date: 2026-10-08 10:16:05.695730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd6391130c4f'
down_revision: Union[str, None] = 'ffecd4ec72e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('license_categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('license_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.Enum('A1', 'A', 'B1', 'B', 'C1', 'C', 'CE', 'D1', 'D', 'DE', 'G1', 'G', 'J', name='vehiclecategory'), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('expiry_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['license_id'], ['licenses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_id', 'category')
    )
    op.create_index(op.f('ix_license_categories_license_id'), 'license_categories', ['license_id'], unique=False)
    op.add_column('applications', sa.Column('requested_categories', sa.JSON(), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'requested_categories')
    op.drop_index(op.f('ix_license_categories_license_id'), table_name='license_categories')
    op.drop_table('license_categories')
    sa.Enum(name='vehiclecategory').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
