"""add appeals table and fine payment method

Revision ID: e19dd989d149
Revises: 727c78b70629
Create Date: 2026-09-03 05:17:04.696308

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e19dd989d149"
down_revision: Union[str, None] = "727c78b70629"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "appeals",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("fine_id", sa.Uuid(), nullable=False),
        sa.Column("driver_id", sa.Uuid(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "UPHELD", "OVERTURNED", name="appealstatus"),
            nullable=False,
        ),
        sa.Column("resolved_by", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["driver_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["fine_id"], ["fines.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["resolved_by"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("fine_id"),
    )
    # create_table's CREATE TYPE for appealstatus happens implicitly via the
    # table DDL above, but a bare ADD COLUMN does not create the enum type
    # for us -- do it explicitly before referencing it.
    payment_method_enum = sa.Enum("CARD", "BANK", "WALLET", name="paymentmethod")
    payment_method_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "fines", sa.Column("payment_method", payment_method_enum, nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("fines", "payment_method")
    sa.Enum(name="paymentmethod").drop(op.get_bind(), checkfirst=True)
    op.drop_table("appeals")
    # ### end Alembic commands ###
