"""add notifications, road incidents, and push token

Revision ID: f4fa8483d762
Revises: 480bf96b774d
Create Date: 2026-09-07 03:18:04.790185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4fa8483d762'
down_revision: Union[str, None] = '480bf96b774d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('LICENSE_APPROVED', 'LICENSE_REJECTED', 'FINE_ISSUED', 'LICENSE_SUSPENDED', 'PAYMENT_CONFIRMED', 'APPEAL_UPHELD', 'APPEAL_OVERTURNED', 'BADGE_CHANGED', 'NEARBY_INCIDENT', name='notificationtype'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('road_incidents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reporter_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('ACCIDENT', 'TRAFFIC', 'ROAD_BLOCK', 'FLOOD', 'CONSTRUCTION', 'BREAKDOWN', 'HAZARD', 'OTHER', name='roadincidenttype'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='roadincidentseverity'), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CLEARED', 'EXPIRED', name='roadincidentstatus'), nullable=False),
    sa.Column('confirmation_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('push_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'push_token')
    op.drop_table('road_incidents')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
