"""create licenses table

Revision ID: fa7391ba98d1
Revises: 3df1b12c6ccb
Create Date: 2026-09-02 13:41:26.019682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa7391ba98d1'
down_revision: Union[str, None] = '3df1b12c6ccb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('licenses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('driver_id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('license_no', sa.String(length=32), nullable=False),
    sa.Column('qr_token', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', name='licensestatus'), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('expiry_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id')
    )
    op.create_index(op.f('ix_licenses_driver_id'), 'licenses', ['driver_id'], unique=False)
    op.create_index(op.f('ix_licenses_license_no'), 'licenses', ['license_no'], unique=True)
    op.create_index(op.f('ix_licenses_qr_token'), 'licenses', ['qr_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_licenses_qr_token'), table_name='licenses')
    op.drop_index(op.f('ix_licenses_license_no'), table_name='licenses')
    op.drop_index(op.f('ix_licenses_driver_id'), table_name='licenses')
    op.drop_table('licenses')
    # ### end Alembic commands ###
